name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  tox:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: python -m pip install --upgrade pip tox
      - name: List available tox environments
        run: tox -l -v
      - name: Run tox
        run: tox -e py${{ matrix.python-version//. }}-test
