name: CI

on: [push, pull_request]

jobs:

  ci-runs:
    name: ${{ matrix.os }}, ${{ matrix.tox_env }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allowed_fail }}
    env:
      PYTEST_ADDOPTS: --color=yes
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: macos-latest
            python: '3.11'
            tox_env: 'py311-test'
            allowed_fail: false
          - os: ubuntu-latest
            python: '3.11'
            tox_env: 'py311-test'
            allowed_fail: false
 
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Print Python, pip, and tox versions
        run: |
          python -c "import sys; print(f'Python {sys.version}')"
          python -c "import pip; print(f'pip {pip.__version__}')"
          python -c "import tox; print(f'tox {tox.__version__}')"
      - name: Run tests
        if: ${{ !matrix.gammapy_data_path }}
        run: tox -e ${{ matrix.tox_env }} -- -n auto
      - name: Upload coverage to codecov
        if: "contains(matrix.tox_env, '-cov')"
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          verbose: true